### ISSUE TITLE
Select Server fo request

### ISSUE THREAD

**Issue by mariofix** [Dorthu/openapi3#106]
Awesome library, thanks!

The file i'm [trying to read](https://www.flow.cl/docs/apiFlow.yaml?v=6) has two servers in it

```yaml
servers:
  - url: 'https://www.flow.cl/api'
    description: Production server (uses live data)
  - url: 'https://sandbox.flow.cl/api'
    description: Sandbox server (uses test data)
``` 

But i noticed in [_get_callable](https://github.com/Dorthu/openapi3/blob/60fb34c6c3a35ebb9fa17d2dca51b010a6aa05ae/openapi3/openapi.py#L202C25-L202C25) that you select the first one in the array

```py
        base_url = self.servers[0].url
``` 

is there another way to select the server to send the request?
