### ISSUE TITLE
Read custom tags

### ISSUE THREAD

**Issue by VedavyasBhatJupiter** [Dorthu/openapi3#95]
I have custom tags on some `Schema` objects. I can't find it in the object, though. Is it possible?

```
components:
  schemas:
    User
      properties:
        userId:
          type: string
          x-custom-tag-1: someValue
          x-custom-tag-2: someOtherValue
```
